# Generated by Django 6.0.3 on 2026-03-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_hp', models.IntegerField()),
                ('current_hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
