# Generated by Django 6.0.3 on 2026-03-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_encounter_combatant'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
    ]
