# Generated by Django 6.0.3 on 2026-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0003_encounter_current_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='current_turn',
            field=models.IntegerField(default=1),
        ),
    ]
